name: contribution-snake

on:
   #run every midnight
  schedule:
    - cron: "0 0 * * *"

  workflow-dispatch:

  #run on every push to the main branch
  push:
    branches:
    - main

jobs:
  runs-on: ubuntu-latest
  timeout-minutes: 10

  steps:
    - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg